name = "modpack"
author = "Glitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e5d96eb66b8951f00789f3434fe050320f0fb66ac51ef14ff36fc74cec039f6"

[versions]
minecraft = "1.18.2"
quilt = "0.17.3"
