name = "modpack"
author = "Glitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae8ff187b20517272953e5491da457b0dc4a440594dbe0a0c9a5490bb8f26636"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"
