name = "modpack"
author = "Glitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c514bc50c98e8733f0334978d55377b5f9b42cc6dfba6ae3fa640df6ba586286"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"
