name = "modpack"
author = "Glitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b20f6c36b92a42b67c71460af3340b2544b0a7c057d50532b07c85deb596788a"

[versions]
minecraft = "1.18.2"
quilt = "0.17.2-beta.2"
