name = "modpack"
author = "Glitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27ca7d6614e72932b6ce3177076bbf3182cea2037ffd4de1e9b1d9d038715531"

[versions]
minecraft = "1.18.2"
quilt = "0.17.3"
